### PR TITLE
Bump aiohttp to 3.9.5 (for Python 3.12)

### PR DESCRIPTION
**Pull request by therealrainman**
Update to latest aiohttp for Python 3.12 compatibility

### CODE REVIEW

**Comment by therealrainman** [comment]
Related issue: #21

**Comment by Naviamold1** [comment]
Please

**Comment by AsgerD1000** [comment]
you can come around it by first installing the lates version of aiohttp: pip install aiohttp==3.9.5 and then pip install chess.com --no-deps

**Comment by Naviamold1** [comment]
> you can come around it by first installing the lates version of aiohttp: pip install aiohttp==3.9.5 and then pip install chess.com --no-deps

Not a bad idea but I just [forked](https://github.com/Naviamold1/chess.com) this project and published a maintained version onto pypi

**Comment by btakashi** [comment]
I agree - going to use the forked project for now.

**Comment by sarartur** [comment]
Sorry about this, have not be looking at this repo, merging now

**Pull request merged**
